In [1]:
import numpy as np

# Array Manipulation

In [3]:
arr=np.random.randint(1,10,(4,4))

In [4]:
arr

array([[5, 7, 3, 9],
       [3, 5, 2, 8],
       [8, 8, 9, 4],
       [4, 1, 2, 1]])

In [5]:
arr.reshape(2,-1)

array([[5, 7, 3, 9, 3, 5, 2, 8],
       [8, 8, 9, 4, 4, 1, 2, 1]])

In [6]:
arr.T

array([[5, 3, 8, 4],
       [7, 5, 8, 1],
       [3, 2, 9, 2],
       [9, 8, 4, 1]])

In [7]:
arr.flatten() # creates 1D array


array([5, 7, 3, 9, 3, 5, 2, 8, 8, 8, 9, 4, 4, 1, 2, 1])

In [8]:
np.expand_dims(arr,axis=1) # it creates 2d to 3d respect of col for case of row axis =1

array([[[5, 7, 3, 9]],

       [[3, 5, 2, 8]],

       [[8, 8, 9, 4]],

       [[4, 1, 2, 1]]])

In [10]:
data=np.expand_dims(arr,axis=0)

In [11]:
data

array([[[5, 7, 3, 9],
        [3, 5, 2, 8],
        [8, 8, 9, 4],
        [4, 1, 2, 1]]])

In [12]:
np.squeeze(data) # decreses the diamention


array([[5, 7, 3, 9],
       [3, 5, 2, 8],
       [8, 8, 9, 4],
       [4, 1, 2, 1]])

In [14]:
np.repeat(data ,4) # each data will repeat 4 times

array([5, 5, 5, 5, 7, 7, 7, 7, 3, 3, 3, 3, 9, 9, 9, 9, 3, 3, 3, 3, 5, 5,
       5, 5, 2, 2, 2, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9,
       4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1])

In [17]:
new=np.array([[1],[2],[3],[4]])

In [18]:
new

array([[1],
       [2],
       [3],
       [4]])

In [19]:
np.roll(new,3) # rotate the array 3 time

array([[2],
       [3],
       [4],
       [1]])

In [20]:
np.roll(new,1)

array([[4],
       [1],
       [2],
       [3]])

In [21]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# binary operation

In [22]:
arr1=np.random.randint(1,10,(4,3))
arr2=np.random.randint(1,10,(4,3))

In [23]:
arr1

array([[4, 9, 7],
       [3, 6, 9],
       [1, 1, 5],
       [4, 2, 5]])

In [24]:
arr2

array([[3, 3, 9],
       [5, 7, 7],
       [3, 5, 5],
       [8, 5, 6]])

In [25]:
arr1+arr2


array([[ 7, 12, 16],
       [ 8, 13, 16],
       [ 4,  6, 10],
       [12,  7, 11]])

In [26]:
arr1*arr2

array([[12, 27, 63],
       [15, 42, 63],
       [ 3,  5, 25],
       [32, 10, 30]])

In [27]:
arr1/arr2

array([[1.33333333, 3.        , 0.77777778],
       [0.6       , 0.85714286, 1.28571429],
       [0.33333333, 0.2       , 1.        ],
       [0.5       , 0.4       , 0.83333333]])

In [28]:
arr1**arr2 #power operation

array([[      64,      729, 40353607],
       [     243,   279936,  4782969],
       [       1,        1,     3125],
       [   65536,       32,    15625]])

In [30]:
~arr1 #negation operation

array([[ -5, -10,  -8],
       [ -4,  -7, -10],
       [ -2,  -2,  -6],
       [ -5,  -3,  -6]])

In [31]:
arr1>arr2

array([[ True,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

# string operation

In [36]:
arr=np.array(['anisha','parveen'])

In [35]:
arr

array(['anisha', 'arveen'], dtype='<U6')

In [38]:
arr[0].upper()

'ANISHA'

In [40]:
np.char.upper(arr)

array(['ANISHA', 'PARVEEN'], dtype='<U7')

In [41]:
np.char.capitalize(arr)

array(['Anisha', 'Parveen'], dtype='<U7')

In [43]:
#every string funtion available in python can use it in numpy  using '.char' class

# mathematical funtion

In [45]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849,  0.6569866 ],
       [ 0.14112001, -0.2794155 ,  0.41211849],
       [ 0.84147098,  0.84147098, -0.95892427],
       [-0.7568025 ,  0.90929743, -0.95892427]])

In [46]:
np.cos(arr1)

array([[-0.65364362, -0.91113026,  0.75390225],
       [-0.9899925 ,  0.96017029, -0.91113026],
       [ 0.54030231,  0.54030231,  0.28366219],
       [-0.65364362, -0.41614684,  0.28366219]])

In [47]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566,  0.87144798],
       [-0.14254654, -0.29100619, -0.45231566],
       [ 1.55740772,  1.55740772, -3.38051501],
       [ 1.15782128, -2.18503986, -3.38051501]])

In [48]:
np.log10(arr1)

array([[0.60205999, 0.95424251, 0.84509804],
       [0.47712125, 0.77815125, 0.95424251],
       [0.        , 0.        , 0.69897   ],
       [0.60205999, 0.30103   , 0.69897   ]])

In [50]:
np.power(arr1,2)

array([[16, 81, 49],
       [ 9, 36, 81],
       [ 1,  1, 25],
       [16,  4, 25]])

In [51]:
np.mean(arr1)

4.666666666666667

In [52]:
np.median(arr1)

4.5

In [53]:
np.std(arr1)

2.6246692913372702

In [55]:
np.max(arr1)

9

In [56]:
np.min(arr1)

1

In [57]:
arr1-arr2

array([[ 1,  6, -2],
       [-2, -1,  2],
       [-2, -4,  0],
       [-4, -3, -1]])

In [58]:
np.subtract(arr1,arr2)

array([[ 1,  6, -2],
       [-2, -1,  2],
       [-2, -4,  0],
       [-4, -3, -1]])

In [59]:
np.multiply(arr1,arr2)

array([[12, 27, 63],
       [15, 42, 63],
       [ 3,  5, 25],
       [32, 10, 30]])

In [60]:
np.mod(arr1,arr2)

array([[1, 0, 7],
       [3, 6, 2],
       [1, 1, 0],
       [4, 2, 5]])

In [63]:
np.add(arr1,arr2)

array([[ 7, 12, 16],
       [ 8, 13, 16],
       [ 4,  6, 10],
       [12,  7, 11]])

# sort,search & count


In [80]:
arr=np.array([5,6,3,8,1,9,0,9,1])

In [65]:
arr


array([5, 6, 3, 8, 1, 9, 0, 9, 1])

In [66]:
np.sort(arr)

array([0, 1, 1, 3, 5, 6, 8, 9, 9])

In [68]:
np.searchsorted(arr,4)

7

In [74]:
arr1=np.array([1,-1,0,0,0,0,0,0,9])

In [75]:
np.count_nonzero(arr1)

3

In [77]:
np.where(arr1<0)

(array([1]),)

In [78]:
np.where(arr1>0)

(array([0, 8]),)

In [82]:
np.extract(arr>2,arr)

array([5, 6, 3, 8, 9, 9])

# byte swapping

In [83]:
arr1

array([ 1, -1,  0,  0,  0,  0,  0,  0,  9])

In [84]:
arr.byteswap()

array([360287970189639680, 432345564227567616, 216172782113783808,
       576460752303423488,  72057594037927936, 648518346341351424,
                        0, 648518346341351424,  72057594037927936])

In [85]:
arr

array([5, 6, 3, 8, 1, 9, 0, 9, 1])

In [86]:
arr.byteswap(True)

array([360287970189639680, 432345564227567616, 216172782113783808,
       576460752303423488,  72057594037927936, 648518346341351424,
                        0, 648518346341351424,  72057594037927936])

In [87]:
arr

array([360287970189639680, 432345564227567616, 216172782113783808,
       576460752303423488,  72057594037927936, 648518346341351424,
                        0, 648518346341351424,  72057594037927936])

# copies & views

In [88]:
arr=np.array([5,6,3,8,1,9,0,9,1])

In [91]:

b=arr # shallow copy
a=arr.view() #equivalent as shallow copy

In [90]:
b

array([5, 6, 3, 8, 1, 9, 0, 9, 1])

In [92]:
c=np.copy(arr) #deep copy


# matrix library

In [93]:
import numpy.matlib as nm

In [95]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [96]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [103]:
arr1=np.random.randint(1,10,(4,3))
arr2=np.random.randint(1,10,(3,3))

In [100]:
arr1

array([[2, 1, 5],
       [2, 3, 8],
       [5, 1, 3],
       [2, 6, 5]])

In [104]:
arr2

array([[5, 4, 7],
       [4, 6, 9],
       [7, 6, 9]])

In [105]:
np.dot(arr1,arr2)

array([[119, 118, 184],
       [ 83,  80, 125],
       [ 36,  46,  70],
       [120, 108, 171]])

In [106]:
arr1@arr2

array([[119, 118, 184],
       [ 83,  80, 125],
       [ 36,  46,  70],
       [120, 108, 171]])