# part one

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [4]:
arr=np.array(l)

In [5]:
type(arr) # N diamentional array

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])

In [11]:
arr1.ndim # it returns diamention of the array

2

In [12]:
arr.ndim

1

In [17]:
mat=np.matrix(l) #in case of matrix the minimum diamention will be two
mat   

matrix([[1, 2, 3, 4, 5]])

In [15]:
np.asanyarray(l) # it converts into array

array([1, 2, 3, 4, 5])

In [18]:
np.asanyarray(mat) #it is not converting because matrix is a subclass of array so, it is already an array


matrix([[1, 2, 3, 4, 5]])

In [20]:
arr=[1,2,3]
a=arr
arr[0]=100

In [21]:
arr

[100, 2, 3]

In [22]:
a

[100, 2, 3]

In [25]:
# as we can we if we change arr a will also change because shallow copy is performing here.
#to overcome this situation we use deep copy which as follows:

In [28]:
b=np.copy(arr)
b

array([100,   2,   3])

In [29]:
arr

[100, 2, 3]

In [31]:
arr[0]=225
arr

[225, 2, 3]

In [32]:
b

array([100,   2,   3])

In [33]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
np.fromfunction(lambda i,j: i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [38]:
iterable=list(i*i for i in range(5))
iterable

[0, 1, 4, 9, 16]

In [39]:
np.fromiter(iterable,float) # using this we can generate the dataset

array([ 0.,  1.,  4.,  9., 16.])

In [40]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [42]:
np.fromstring('1 2 3 4 5 6 9 8 7',sep =' ')

array([1., 2., 3., 4., 5., 6., 9., 8., 7.])

In [43]:
np.fromstring('1 ,2, 3, 4, 5, 6 ,9 ,8, 7',sep =', ')

array([1., 2., 3., 4., 5., 6., 9., 8., 7.])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr1.size # row*col

6

In [46]:
arr1.shape # dimention

(2, 3)

In [48]:
arr1.dtype

dtype('int64')

# part two

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
#list(range(0.5,5.5)) it will show error as range function only works on integer

In [5]:
np.arange(0.5,5.5) # it is alternative of range function for case of float

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.linspace(1,5,20) # it will give 20 data between 1 to 5

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [9]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((4,3)) #2d dataset

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,4,2)) #3d dataset

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
arr=np.ones((3,4))

In [21]:
arr+5 #every element will be added it is known as broadcastiong 

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [22]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
import pandas as pd

In [24]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [25]:
np.random.rand(10)

array([0.87222714, 0.30020641, 0.49364832, 0.37073299, 0.82407072,
       0.25356356, 0.40657312, 0.18094048, 0.92809647, 0.46888656])

In [26]:
np.random.rand(2,3)

array([[0.404154  , 0.43261383, 0.76099591],
       [0.37599576, 0.34737529, 0.82021351]])

In [27]:
np.random.randn(2,3) #it gives standard normal data where mean =0,sd=1

array([[ 0.80558905, -0.42523914, -1.58696137],
       [ 0.13479311, -1.77930275, -1.47557825]])

In [29]:
arr2=np.random.randint(1,5,(3,4))

In [30]:
arr2

array([[2, 1, 2, 3],
       [4, 1, 4, 1],
       [1, 3, 2, 1]])

In [31]:
arr2.size

12

In [32]:
arr2.shape

(3, 4)

In [35]:
arr2.reshape(4,3) # here the size / number data will change so we can not change thw size but we can change the diamention

array([[2, 1, 2],
       [3, 4, 1],
       [4, 1, 1],
       [3, 2, 1]])

In [36]:
arr2.reshape(6,2)

array([[2, 1],
       [2, 3],
       [4, 1],
       [4, 1],
       [1, 3],
       [2, 1]])

In [37]:
# but we cannot do this arr2.reshape(4,4)

In [38]:
arr2.reshape(6,-1) # we can also will -ve value it will atomatically assume another possible diamention


array([[2, 1],
       [2, 3],
       [4, 1],
       [4, 1],
       [1, 3],
       [2, 1]])

In [39]:
arr2.reshape(6,-1,1)

array([[[2],
        [1]],

       [[2],
        [3]],

       [[4],
        [1]],

       [[4],
        [1]],

       [[1],
        [3]],

       [[2],
        [1]]])

In [46]:
arr3=np.random.randint(1,10,(5,6))

In [50]:
arr3

array([[8, 9, 6, 1, 4, 1],
       [6, 1, 2, 1, 6, 2],
       [7, 7, 6, 4, 6, 8],
       [1, 2, 6, 1, 7, 5],
       [1, 6, 2, 4, 3, 3]])

In [59]:

for i in arr3:
    for j in i:
        if j>8:
            print(j,end=",")
    print("")    
    

9,






In [60]:
arr3>8

array([[False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [61]:
arr3[arr3>8]

array([9])

In [62]:
arr3

array([[8, 9, 6, 1, 4, 1],
       [6, 1, 2, 1, 6, 2],
       [7, 7, 6, 4, 6, 8],
       [1, 2, 6, 1, 7, 5],
       [1, 6, 2, 4, 3, 3]])

In [63]:
arr3[0]

array([8, 9, 6, 1, 4, 1])

In [65]:
arr3[0,1]

9

In [66]:
arr3[2:4,[2,3]]

array([[6, 4],
       [6, 1]])

In [67]:
arr4=np.random.randint(1,3,(3,3))
arr5=np.random.randint(1,3,(3,3))

In [68]:
arr4

array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [69]:
arr5

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [70]:
arr4+arr5

array([[3, 3, 3],
       [2, 4, 2],
       [4, 3, 4]])

In [72]:
arr4/arr5

array([[2. , 2. , 2. ],
       [1. , 1. , 1. ],
       [1. , 0.5, 1. ]])

In [73]:
arr4*arr5 # it is not a matrix multiplication its just a index multiplication

array([[2, 2, 2],
       [1, 4, 1],
       [4, 2, 4]])

In [74]:
#matrix multiplication use "@"
arr4@arr5

array([[ 8, 10,  8],
       [ 5,  7,  5],
       [ 7,  8,  7]])

In [75]:
# in python if we give arr/0 it will show error but in numpuy it will give infinite

In [76]:
arr4/0

/tmp/ipykernel_104/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [85]:
arr= np.zeros((3,3))

In [79]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
a=np.array([[1,2,3]])

In [87]:
arr+a


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [95]:
arr= np.zeros((3,5))

In [96]:
b=a.T

In [97]:
b

array([[1],
       [2],
       [3]])

In [98]:
arr+b

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [103]:
np.sqrt(arr2)

array([[1.41421356, 1.        , 1.41421356, 1.73205081],
       [2.        , 1.        , 2.        , 1.        ],
       [1.        , 1.73205081, 1.41421356, 1.        ]])

In [105]:
np.log10(arr2)

array([[0.30103   , 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.        , 0.60205999, 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.        ]])

In [106]:
np.exp(arr2)

array([[ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692],
       [54.59815003,  2.71828183, 54.59815003,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 ,  2.71828183]])

In [107]:
np.min(arr2)

1

In [108]:
np.max(arr2)

4